[language-server.pyright]
command = "pyright-langserver"
args = ["--stdio"]

[[language]]
name = "rust"
auto-format = true

[[language]]
name = "c"
auto-format = true

[[language]]
name = "cpp"
auto-format = true

[[language]]
name = "python"
language-servers = ["pyright"]
formatter = { command = "black", args = ["--quiet", "-"] }
auto-format = true

[[language]]
name = "markdown"
text-width = 80

[[language]]
name = "ocaml"
formatter = { command = "ocamlformat", args = ["-q", "--name=foo.ml", "-"] }
auto-format = true

[[language]]
name = "cmake"
auto-format = true
formatter = { command = "cmake-format", args = ["-"] }
