[language-server.scls]
command = "simple-completion-language-server"

[language-server.pyright]
command = "pyright-langserver"
args = ["--stdio"]

[language-server.gpt]
command = "helix-gpt"

[[language]]
name = "rust"
auto-format = true
language-servers = ["rust-analyzer", "gpt"]

[[language]]
name = "c"
auto-format = true

[[language]]
name = "cpp"
auto-format = true

[[language]]
name = "git-commit"
language-servers = ["scls"]

[[language]]
name = "python"
language-servers = ["pyright", "gpt"]
formatter = { command = "black", args = ["--quiet", "-"] }
auto-format = true

[[language]]
name = "latex"
language-servers = ["texlab", "scls"]
